-- DEADLOCK
GO
CREATE OR ALTER PROCEDURE D1 AS
BEGIN TRANSACTION
	UPDATE Manager1 SET ManagerPhone = '0711111111'
	WHERE ManagerId = 1

	WAITFOR DELAY '00:00:10'

	UPDATE Gifts SET Description = 'Description new'
	WHERE GiftId = 1
COMMIT TRANSACTION