-- PHANTOM READS

BEGIN TRANSACTION T
	--SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
	SELECT * FROM T1
	WHERE Email LIKE '%@gmail.com'

	WAITFOR DELAY '00:00:10'

	SELECT * FROM T1
	WHERE Email LIKE '%@gmail.com'
COMMIT TRANSACTION T